version: '3.5'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

services:
### tomcat ####################################################
    tomcat1:
      container_name: tomcat1
      image: tomcat:${TOMCAT_VERSION}
      networks:
        - frontend
        - backend
      volumes:
        - ./tomcat/webapps/demo.war:/usr/local/tomcat/webapps/demo.war
        - ./tomcat/logs1:/usr/local/tomcat/logs
      # restart: always
### tomcat ####################################################
    tomcat2:
      container_name: tomcat2
      image: tomcat:${TOMCAT_VERSION}
      networks:
        - frontend
        - backend
      volumes:
        - ./tomcat/webapps/demo.war:/usr/local/tomcat/webapps/demo.war
        - ./tomcat/logs2:/usr/local/tomcat/logs
### NGINX Server #########################################
    nginx:
      build:
        context: ./nginx
        args:
          - CHANGE_SOURCE=${CHANGE_SOURCE}
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        - ${NGINX_SSL_PATH}:/etc/nginx/ssl
        - ./html:/var/www/public
      extra_hosts:
        - "web1:127.0.0.1"
        - "web2:127.0.0.1"
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      networks:
        - frontend
        - backend
